// Package docs renders the governed, drift-checked documentation
// (plans/os-16e55c11.md D1): the lifecycle, the capability lanes, the
// exit codes and the per-lane worker docs, each generated from the same
// table the machinery reads — never from prose. `seed docs generate`
// writes the output under docs/generated/; `seed docs check`
// regenerates and diffs, so a hand edit or a table change that the
// committed prose has not caught fails as drift.
package docs

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/shaunlmason/open-seed-v2/internal/admit"
	"github.com/shaunlmason/open-seed-v2/internal/keyring"
	"github.com/shaunlmason/open-seed-v2/internal/lane"
	"github.com/shaunlmason/open-seed-v2/internal/transition"
)

// GenDir is the repo-relative directory the generated docs live under.
const GenDir = "docs/generated"

// preamble is the banner every generated file carries, so a reader on
// the forge knows the file is derived and where the authority is.
func preamble(from string) string {
	return "<!-- GENERATED by `seed docs generate` from " + from + ". Do not edit by hand; run `seed docs check`. -->\n\n"
}

// Generate renders every governed document, returning repo-relative
// path -> content. root is the repository root (the tree `docs check`
// runs against); the lifecycle and capability tables are read from the
// embedded table and the keyring, the exit codes from the envelope
// package's own source under root, the lane docs from root/lanes.
func Generate(root string) (map[string]string, error) {
	out := map[string]string{}
	life, err := renderLifecycle()
	if err != nil {
		return nil, fmt.Errorf("lifecycle: %w", err)
	}
	out[filepath.Join(GenDir, "lifecycle.md")] = life
	out[filepath.Join(GenDir, "capabilities.md")] = renderCapabilities()
	ec, err := renderExitCodes(root)
	if err != nil {
		return nil, fmt.Errorf("exit-codes: %w", err)
	}
	out[filepath.Join(GenDir, "exit-codes.md")] = ec
	conf, err := renderConformance(root)
	if err != nil {
		return nil, fmt.Errorf("conformance: %w", err)
	}
	out[filepath.Join(GenDir, "conformance.md")] = conf
	lanes, err := renderLanes(root)
	if err != nil {
		return nil, fmt.Errorf("lanes: %w", err)
	}
	for name, content := range lanes {
		out[filepath.Join(GenDir, "lanes", name+".md")] = content
	}
	return out, nil
}

// capsFor renders a verb's accepted-capability set as the docs show it:
// the codes in declared order, or the standing-only marker for a verb
// the keyring accepts on active standing alone (the no-fallback rows).
func capsFor(verb string) string {
	caps := keyring.AcceptedCapabilities(verb)
	if len(caps) == 0 {
		return "— (standing only)"
	}
	q := make([]string, len(caps))
	for i, c := range caps {
		q[i] = "`" + c + "`"
	}
	return strings.Join(q, ", ")
}

type tableFile struct {
	States []struct {
		Name     string `json:"name"`
		Initial  bool   `json:"initial"`
		Terminal bool   `json:"terminal"`
	} `json:"states"`
	Transitions []struct {
		Verb      string    `json:"verb"`
		From      *[]string `json:"from"`
		To        string    `json:"to"`
		Exclusive bool      `json:"exclusive"`
	} `json:"transitions"`
}

func renderLifecycle() (string, error) {
	var tf tableFile
	if err := json.Unmarshal(transition.TableJSON(), &tf); err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString(preamble("spec/transitions.json"))
	b.WriteString("# Lifecycle\n\nThe contract lifecycle as `spec/transitions.json` declares it. `spec/lifecycle.md` explains it; this table is the authority for the enumeration.\n\n")
	b.WriteString("## States\n\n| State | Role |\n|---|---|\n")
	for _, s := range tf.States {
		role := "—"
		switch {
		case s.Initial:
			role = "initial"
		case s.Terminal:
			role = "terminal"
		}
		fmt.Fprintf(&b, "| `%s` | %s |\n", s.Name, role)
	}
	b.WriteString("\n## Transitions\n\n| Verb | From | To | Exclusive | Accepted capabilities |\n|---|---|---|---|---|\n")
	for _, r := range tf.Transitions {
		from := "— (birth)"
		if r.From != nil {
			q := make([]string, len(*r.From))
			for i, f := range *r.From {
				q[i] = "`" + f + "`"
			}
			from = strings.Join(q, ", ")
		}
		excl := ""
		if r.Exclusive {
			excl = "yes"
		}
		fmt.Fprintf(&b, "| `%s` | %s | `%s` | %s | %s |\n", r.Verb, from, r.To, excl, capsFor(r.Verb))
	}
	return b.String(), nil
}

func renderCapabilities() string {
	var b strings.Builder
	b.WriteString(preamble("internal/admit affordanceCatalog + internal/keyring AcceptedCapabilities"))
	b.WriteString("# Capabilities\n\nEvery verb the affordance catalog drafts, with the capability set the keyring accepts for it. A verb with no accepted capability is admitted on active standing alone (the no-fallback rows). `spec/actors.md` is the prose; this table is the authority for the enumeration.\n\n")
	b.WriteString("| Verb | Accepted capabilities |\n|---|---|\n")
	for _, v := range admit.CatalogVerbs() {
		fmt.Fprintf(&b, "| `%s` | %s |\n", v, capsFor(v))
	}
	return b.String()
}

func renderLanes(root string) (map[string]string, error) {
	dir := filepath.Join(root, "lanes")
	ms, err := lane.Load(dir)
	if err != nil {
		return nil, err
	}
	out := map[string]string{}
	for _, m := range ms {
		doc, err := lane.Resolve(dir, m)
		if err != nil {
			return nil, fmt.Errorf("resolve %s: %w", m.Lane, err)
		}
		out[m.Lane] = preamble("lanes/"+m.Lane+".json") + doc
	}
	return out, nil
}
