package importer

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/shaunlmason/open-seed-v2/internal/admit"
	"github.com/shaunlmason/open-seed-v2/internal/artifact"
	"github.com/shaunlmason/open-seed-v2/internal/imported"
	"github.com/shaunlmason/open-seed-v2/internal/transition"
	"github.com/shaunlmason/open-seed-v2/internal/version"
)

// placeholderDigest stands in for the manifest digest on the passes
// that discover positions; the final pass cites the real one.
const placeholderDigest = "0000000000000000000000000000000000000000000000000000000000000000"

// maxInline bounds a string the transform carries inline in a payload;
// the classification lint's cap is 512 bytes per string with a 1024
// byte aggregate, and a packet carries several.
const maxInline = 300

// cardState is the per-subject bookkeeping the transform keeps.
type cardState struct {
	receipt string
	prNum   string
	merged  string
	packet  json.RawMessage
	handoff string // artifact digest of the handoff, when one exists
}

// replay is one pass of the transform over the source.
type replay struct {
	src    *Source
	table  *Table
	ros    *roster
	byFP   map[string]*actor
	op     *signer
	opAct  *actor
	ch     *chain
	repo   *repoLookup
	head   string
	anchor *Anchor
	now    time.Time

	artifacts   map[string][]byte
	disp        []Disposition
	cards       map[string]*cardState
	unresolved  []string
	consumed    map[string]bool
	importedPos int
}

func newReplay(src *Source, table *Table, ros *roster, op *signer, repo string, anchor *Anchor, now time.Time) *replay {
	r := &replay{src: src, table: table, ros: ros, op: op, head: src.Export.Head, anchor: anchor, now: now,
		artifacts: map[string][]byte{}, byFP: map[string]*actor{}, repo: newRepoLookup(repo),
		opAct: &actor{name: "the importing operator", kind: "operator", s: op, operator: true, verbs: map[string]bool{}}}
	for _, a := range ros.all() {
		r.byFP[a.s.fp] = a
	}
	return r
}

func (r *replay) reset() {
	r.disp = nil
	r.cards = map[string]*cardState{}
	r.unresolved = nil
	r.consumed = map[string]bool{}
	r.ros.reset()
}

func (r *replay) put(b []byte) string {
	d := artifact.Digest(b)
	r.artifacts[d] = b
	return d
}

func (r *replay) note(d *Disposition, s string) {
	if d.Note == "" {
		d.Note = s
		return
	}
	d.Note += "; " + s
}

func (r *replay) card(subject string) *cardState {
	cs, ok := r.cards[subject]
	if !ok {
		cs = &cardState{}
		r.cards[subject] = cs
	}
	return cs
}

func parseTS(s string) (time.Time, error) {
	t, err := time.Parse(time.RFC3339, s)
	if err != nil {
		return time.Time{}, fmt.Errorf("ts %q is not RFC 3339", s)
	}
	return t, nil
}

func clip(s string) string {
	s = strings.TrimSpace(s)
	if len(s) <= maxInline {
		return s
	}
	cut := maxInline
	for cut > 0 && (s[cut]&0xC0) == 0x80 {
		cut--
	}
	return s[:cut] + "…"
}

// run is one complete pass: genesis, the upgrades to seed/5,
// system.imported citing the manifest digest, the enrollments, the
// history, the file dispositions, the suspensions.
func (r *replay) run(manifestDigest string, dry bool) error {
	r.reset()
	ch, err := newChain(r.op, r.now, dry)
	if err != nil {
		return err
	}
	r.ch = ch
	for _, a := range r.ros.all() {
		ch.keys[a.s.fp] = a.s.pub
	}
	if err := ch.upgradeTo(r.op, version.Seed5, r.now); err != nil {
		return err
	}
	payload, err := imported.Render(r.head, r.anchor.Tag, manifestDigest)
	if err != nil {
		return err
	}
	if r.importedPos, err = ch.append(r.op, imported.Verb, imported.Subject, payload, r.now, "importer"); err != nil {
		return err
	}
	for _, a := range r.ros.all() {
		if a == r.ros.ver && !dry && !a.needed {
			continue
		}
		if err := r.enroll(a); err != nil {
			return err
		}
	}
	for _, e := range r.src.Entries {
		if err := r.entry(e); err != nil {
			return err
		}
	}
	for _, id := range r.src.CardIDs {
		if err := r.cardRecord(id); err != nil {
			return err
		}
	}
	ids := make([]string, 0, len(r.src.Handoffs))
	for id := range r.src.Handoffs {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		h := r.src.Handoffs[id]
		r.disp = append(r.disp, Disposition{Record: h.Path, Artifact: r.put([]byte(h.Raw))})
	}
	for _, p := range r.src.Mail {
		if err := r.mail(p); err != nil {
			return err
		}
	}
	for _, p := range r.src.Other {
		r.disp = append(r.disp, Disposition{Record: p, Artifact: r.put([]byte(r.src.Export.Files[p])), Note: "a file of no known kind, stored as it was exported"})
	}
	for _, a := range r.ros.all() {
		if a.enrolled == 0 {
			continue
		}
		pos, err := ch.append(r.op, "actor.suspended", a.s.fp, []byte(`{"reason": "imported: the key was generated by the importer for a predecessor's actor name and holds no standing an operator granted"}`), r.now, "importer")
		if err != nil {
			return err
		}
		a.suspended = pos
	}
	return nil
}

func (r *replay) enroll(a *actor) error {
	payload, _ := json.Marshal(map[string]string{"key": a.pubHex(), "kind": a.kind, "name": a.name})
	pos, err := r.ch.append(r.op, "actor.enrolled", a.s.fp, payload, r.now, "importer")
	if err != nil {
		return err
	}
	a.enrolled = pos
	for _, g := range a.grants {
		if _, err := r.ch.append(r.op, "actor.granted", a.s.fp, []byte(`{"capability": "`+g+`"}`), r.now, "importer"); err != nil {
			return err
		}
	}
	return nil
}

// emit signs one record with an identity and records it on the
// disposition.
func (r *replay) emit(a *actor, verb, subject string, payload []byte, ts time.Time, d *Disposition) (int, error) {
	s := r.op
	if a != nil {
		s = a.s
		a.verbs[verb] = true
	}
	pos, err := r.ch.append(s, verb, subject, payload, ts, d.Record)
	if err != nil {
		return 0, err
	}
	d.Events = append(d.Events, Placed{Position: pos, Verb: verb, Subject: subject, Signer: s.fp})
	return pos, nil
}

// withFence adds the fence citation the boundary requires: a held
// subject's lifecycle moves and the holder's (or a prior claimant's)
// facts cite the active fence; nothing else may.
func (r *replay) withFence(subject string, fp, verb string, payload map[string]any) []byte {
	s, ok := r.ch.state(subject)
	if ok && s.Claim != nil {
		if r.ch.ctx.Table.Allows(s.State, verb) || fp == s.Claim.Holder || s.PriorClaimants[fp] {
			payload["fence"] = strconv.Itoa(s.Claim.Fence)
		}
	}
	b, _ := json.Marshal(payload)
	return b
}

func (r *replay) entry(e Entry) error {
	d := Disposition{Record: fmt.Sprintf("run-log#%d", e.Index), Verb: e.Verb, Actor: e.Actor}
	row, ok := r.table.Verbs[e.Verb]
	if !ok {
		return &Refusal{Kind: "import_unmapped", Detail: fmt.Sprintf("run-log verb %q has no row in the transform table", e.Verb)}
	}
	if row.Drop != "" {
		d.Drop = row.Drop
		r.disp = append(r.disp, d)
		return nil
	}
	ts, err := parseTS(e.TS)
	if err != nil {
		return fmt.Errorf("%s: %v", d.Record, err)
	}
	a := r.ros.get(e.Actor)
	if a == nil {
		return fmt.Errorf("%s: actor %q is not in the identity plan", d.Record, e.Actor)
	}
	subject := e.Task
	if subject == "" {
		r.note(&d, "the entry names no task, so it became nothing")
		r.disp = append(r.disp, d)
		return nil
	}
	switch e.Verb {
	case "create":
		if _, exists := r.ch.state(subject); exists {
			r.note(&d, "the subject already existed")
		} else {
			err = r.file(subject, a, ts, &d)
		}
	case "promote":
		err = r.moveTo(subject, "ready", a, ts, &d)
	case "claim":
		err = r.moveTo(subject, "in_progress", a, ts, &d)
	case "release":
		err = r.moveTo(subject, "ready", a, ts, &d)
	case "transition":
		if moved, present := e.Data["transitioned"].(bool); present && !moved {
			r.note(&d, "v1 recorded that nothing transitioned")
			break
		}
		to, known := r.table.States[e.Str("to")]
		if !known {
			return &Refusal{Kind: "import_unmapped", Detail: fmt.Sprintf("%s: card state %q has no row in the transform table", d.Record, e.Str("to"))}
		}
		err = r.moveTo(subject, to, a, ts, &d)
	case "plan-unblock":
		if err = r.moveTo(subject, "ready", a, ts, &d); err == nil {
			err = r.respecifyPlan(subject, a, ts, &d)
		}
	case "unblock":
		if moved, present := e.Data["transitioned"].(bool); present && !moved {
			r.note(&d, "v1 recorded that nothing transitioned")
			break
		}
		err = r.moveTo(subject, "ready", a, ts, &d)
	case "cancel":
		err = r.moveTo(subject, "cancelled", a, ts, &d)
	case "close", "accept":
		to := e.Str("to")
		if to == "" {
			to = "done"
		}
		target, known := r.table.States[to]
		if !known {
			return &Refusal{Kind: "import_unmapped", Detail: fmt.Sprintf("%s: card state %q has no row in the transform table", d.Record, to)}
		}
		err = r.moveTo(subject, target, a, ts, &d)
	case "comment":
		err = r.comment(subject, a, e, ts, &d)
	case "attach-evidence":
		r.evidence(subject, e, &d)
	case "record-evidence":
		r.recordEvidence(subject, e, &d)
	default:
		return fmt.Errorf("%s: the table maps %q to an event but the transform has no case for it", d.Record, e.Verb)
	}
	if err != nil {
		return err
	}
	r.disp = append(r.disp, d)
	return nil
}

func (r *replay) title(subject string) string {
	if c := r.src.Cards[subject]; c != nil && strings.TrimSpace(c.Title) != "" {
		return c.Title
	}
	return subject
}

// file is intent.filed: the title as the intent, the table's default
// tier, budget and routing.
func (r *replay) file(subject string, a *actor, ts time.Time, d *Disposition) error {
	routing := r.table.Defaults.Routing
	if c := r.src.Cards[subject]; c != nil && strings.TrimSpace(c.Squad) != "" {
		routing = strings.TrimSpace(c.Squad)
	}
	payload, _ := json.Marshal(map[string]string{
		"intent": clip(r.title(subject)), "tier": r.table.Defaults.Tier,
		"budget": r.table.Defaults.Budget, "routing": routing,
	})
	_, err := r.emit(a, "intent.filed", subject, payload, ts, d)
	return err
}

// adjacency is the lifecycle table as the transform walks it: the
// verb that moves a state to a neighbor. done is reached through the
// verdict chain, which merge.observed stands for here.
var adjacency = map[string]map[string]string{
	"backlog":     {"ready": "contract.specified", "cancelled": "contract.cancelled"},
	"ready":       {"in_progress": "claim.taken", "blocked": "contract.blocked", "cancelled": "contract.cancelled"},
	"in_progress": {"review": "submission.made", "ready": "claim.released", "blocked": "claim.parked"},
	"review":      {"done": "merge.observed", "ready": "contract.returned", "cancelled": "contract.cancelled"},
	"blocked":     {"ready": "contract.unblocked", "cancelled": "contract.cancelled"},
}

// path is the shortest verb sequence from one state to another.
func path(from, to string) []string {
	type node struct {
		state string
		verbs []string
	}
	queue := []node{{state: from}}
	seen := map[string]bool{from: true}
	for len(queue) > 0 {
		n := queue[0]
		queue = queue[1:]
		if n.state == to {
			return n.verbs
		}
		// Ties break toward the honest exit: a release before a park,
		// review before blocked, so a cancel out of in_progress
		// releases the claim rather than parking it.
		var next []string
		for _, s := range []string{"ready", "review", "in_progress", "blocked", "done", "cancelled"} {
			if _, ok := adjacency[n.state][s]; ok {
				next = append(next, s)
			}
		}
		for _, s := range next {
			if !seen[s] {
				seen[s] = true
				queue = append(queue, node{state: s, verbs: append(append([]string{}, n.verbs...), adjacency[n.state][s])})
			}
		}
	}
	return nil
}

func (r *replay) moveTo(subject, target string, a *actor, ts time.Time, d *Disposition) error {
	s, ok := r.ch.state(subject)
	if !ok {
		if err := r.file(subject, a, ts, d); err != nil {
			return err
		}
		r.note(d, "bridge: the subject was filed first")
		s, _ = r.ch.state(subject)
	}
	if s.State == target {
		r.note(d, "already "+target)
		return nil
	}
	steps := path(s.State, target)
	if steps == nil {
		return fmt.Errorf("%s: no lifecycle path from %s to %s", d.Record, s.State, target)
	}
	if len(steps) > 1 {
		r.note(d, fmt.Sprintf("bridge: %s", strings.Join(steps[:len(steps)-1], ", ")))
	}
	for _, verb := range steps {
		if err := r.step(subject, verb, a, ts, d); err != nil {
			return err
		}
	}
	return nil
}

func (r *replay) step(subject, verb string, a *actor, ts time.Time, d *Disposition) error {
	s, _ := r.ch.state(subject)
	switch verb {
	case "contract.specified":
		payload, _ := json.Marshal(map[string]any{"acceptance": map[string]any{"ref": "tasks/" + subject + ".md @ " + r.head, "executable": false}})
		_, err := r.emit(a, verb, subject, payload, ts, d)
		return err
	case "claim.taken":
		_, err := r.emit(a, verb, subject, []byte(`{}`), ts, d)
		return err
	case "claim.released", "claim.parked", "submission.made":
		if s.Claim == nil {
			return fmt.Errorf("%s: %s with no claim on %s", d.Record, verb, subject)
		}
		signer := a
		if a.s.fp != s.Claim.Holder {
			holder := r.byFP[s.Claim.Holder]
			if verb == "claim.released" && !a.operator {
				verb = "claim.reaped"
				r.note(d, "claim.reaped: v1 let "+a.name+" release a claim it did not hold")
			} else {
				signer = holder
				r.note(d, "signed by the holder "+holder.name+": v1 let "+a.name+" move a claim it did not hold")
			}
		}
		payload := r.withFence(subject, signer.s.fp, verb, map[string]any{"packet": r.packet(subject)})
		_, err := r.emit(signer, verb, subject, payload, ts, d)
		return err
	case "contract.blocked", "contract.unblocked", "contract.returned":
		_, err := r.emit(a, verb, subject, r.withFence(subject, a.s.fp, verb, map[string]any{}), ts, d)
		return err
	case "contract.cancelled":
		_, err := r.emit(nil, verb, subject, r.withFence(subject, r.op.fp, verb, map[string]any{}), ts, d)
		return err
	case "merge.observed":
		return r.doneChain(subject, a, ts, d)
	}
	return fmt.Errorf("%s: the transform has no step for %s", d.Record, verb)
}

// packet synthesizes the four-part packet for a subject once, from
// the handoff's mechanical sections; without a handoff the packet says
// so and anchors at the export head.
func (r *replay) packet(subject string) json.RawMessage {
	cs := r.card(subject)
	if cs.packet != nil {
		return cs.packet
	}
	h := r.src.Handoffs[subject]
	acceptance := "imported: " + clip(r.title(subject))
	base := r.head[:12] + ".." + r.head[:12]
	refs := []string{}
	findings := []map[string]string{}
	if h != nil {
		if strings.TrimSpace(h.Task) != "" {
			acceptance = clip(h.Task)
		}
		if sha := h.AnchorSHA(); sha != "" {
			base = sha + ".." + sha
		}
		cs.handoff = r.put([]byte(h.Raw))
		refs = append(refs, h.Path+" @ "+r.head)
		findings = append(findings, map[string]string{"tried": "imported", "outcome": "the packet is the handoff's mechanical sections, never invented prose", "pointer": cs.handoff})
	} else {
		findings = append(findings, map[string]string{"tried": "imported", "outcome": "no handoff was recorded for this card in the export"})
	}
	b, _ := json.Marshal(map[string]any{"acceptance": []string{acceptance}, "decisions": []any{}, "base": base, "refs": refs, "findings": findings})
	cs.packet = b
	return b
}

// doneChain is verdict.rendered(pass) → merge.requested →
// merge.observed. The verdict cites the stored receipt when the card
// attached one, else an import note saying no receipt was recorded:
// merge.overridden overrules a standing fail verdict and nothing
// failed here, so the honest record is a pass over a note that says
// what it is.
func (r *replay) doneChain(subject string, closer *actor, ts time.Time, d *Disposition) error {
	s, _ := r.ch.state(subject)
	if s.Submission == nil {
		return fmt.Errorf("%s: %s is in review with no submission", d.Record, subject)
	}
	cs := r.card(subject)
	verifier := closer
	if closer.operator {
		verifier = r.ros.verifier()
		r.note(d, "verdict by "+VerifierName+": the reconciliation is the operator's")
	} else if s.PriorClaimants[closer.s.fp] || closer.s.fp == s.Submission.Signer {
		verifier = r.ros.verifier()
		r.note(d, "verdict by "+VerifierName+": "+closer.name+" claimed this card")
	}
	receipt := cs.receipt
	if receipt == "" {
		note, _ := json.Marshal(map[string]string{"imported": r.table.Source, "card": subject, "receipt": "none recorded in the export"})
		receipt = r.put(note)
		r.note(d, "verdict over an import note: the card attached no receipt")
	}
	level := admit.LevelAchieved(r.ch.ctx.Records, r.ch.ctx.Table, subject, s, nil)
	payload, _ := json.Marshal(map[string]string{"verdict": "pass", "receipt": receipt, "submission": strconv.Itoa(s.Submission.Pos), "independence": string(level)})
	vpos, err := r.emit(verifier, "verdict.rendered", subject, payload, ts, d)
	if err != nil {
		return err
	}
	requester := r.byFP[s.Submission.Signer]
	if requester == nil {
		requester = closer
	}
	if _, err := r.emit(requester, "merge.requested", subject, r.withFence(subject, requester.s.fp, "merge.requested", map[string]any{"verdict": strconv.Itoa(vpos)}), ts, d); err != nil {
		return err
	}
	merged, pr := r.mergeFacts(subject, cs, d)
	payload, _ = json.Marshal(map[string]string{"merged": merged, "pr": pr})
	_, err = r.emit(closer, "merge.observed", subject, payload, ts, d)
	return err
}

// mergeFacts resolves what the forge merged: the squash commit that
// names the card's PR, else the commit that added the card's receipt,
// else the export head, listed as unresolved.
func (r *replay) mergeFacts(subject string, cs *cardState, d *Disposition) (merged, pr string) {
	if cs.merged != "" {
		return cs.merged, cs.pr()
	}
	if cs.prNum != "" {
		if sha := r.repo.mergeCommit(cs.prNum); sha != "" {
			cs.merged = sha
			return sha, cs.pr()
		}
	}
	if sha := r.repo.addedCommit("receipts/" + subject + ".json"); sha != "" {
		cs.merged = sha
		r.note(d, "merged: the commit that added the card's receipt")
		return sha, cs.pr()
	}
	cs.merged = r.head
	r.unresolved = append(r.unresolved, fmt.Sprintf("%s: no merge commit resolves from --repo; the export head stands in", subject))
	r.note(d, "merged: unresolved, the export head stands in")
	return cs.merged, cs.pr()
}

func (cs *cardState) pr() string {
	if cs.prNum != "" {
		return "pr/" + cs.prNum
	}
	return "imported: no pull request recorded"
}

var (
	pullRE    = regexp.MustCompile(`/pull/(\d+)`)
	receiptRE = regexp.MustCompile(`(receipts/[A-Za-z0-9_.-]+\.json)(?:@([0-9a-f]{7,40}))?`)
)

// findEvidence matches a run-log evidence entry to the card's block by
// kind and instant (v1 wrote both from one clock, within seconds),
// consuming each block once.
func (r *replay) findEvidence(subject, kind, ts string) *Evidence {
	c := r.src.Cards[subject]
	if c == nil {
		return nil
	}
	at, err := parseTS(ts)
	if err != nil {
		return nil
	}
	for i := range c.Evidence {
		ev := &c.Evidence[i]
		key := subject + "/" + ev.ID
		if r.consumed[key] || ev.Kind != kind {
			continue
		}
		et, err := parseTS(ev.TS)
		if err != nil {
			continue
		}
		if diff := et.Sub(at); diff < -10*time.Second || diff > 10*time.Second {
			continue
		}
		r.consumed[key] = true
		return ev
	}
	return nil
}

func (r *replay) evidence(subject string, e Entry, d *Disposition) {
	kind := e.Str("kind")
	ev := r.findEvidence(subject, kind, e.TS)
	if ev == nil {
		line, _ := json.Marshal(map[string]any{"imported": r.table.Source, "record": d.Record, "task": subject, "kind": kind, "actor": e.Actor, "ts": e.TS})
		d.Artifact = r.put(line)
		r.note(d, "no evidence block in the card matched the entry, so the entry itself is the artifact")
		return
	}
	block := fmt.Sprintf("## Evidence %s (%s, %s, %s)\n\n%s\n", ev.ID, ev.Kind, ev.Actor, ev.TS, ev.Text)
	d.Artifact = r.put([]byte(block))
	cs := r.card(subject)
	if m := pullRE.FindStringSubmatch(ev.Text); m != nil && cs.prNum == "" {
		cs.prNum = m[1]
	}
	if kind == "receipt" {
		if m := receiptRE.FindStringSubmatch(ev.Text); m != nil {
			if b := r.repo.file(m[1], m[2]); b != nil {
				cs.receipt = r.put(b)
				r.note(d, "receipt "+m[1]+" stored as "+cs.receipt[:12])
			} else {
				r.unresolved = append(r.unresolved, fmt.Sprintf("%s: %s is not readable from --repo", subject, m[1]))
				r.note(d, "receipt "+m[1]+" not readable from --repo")
			}
		}
	}
}

func (r *replay) recordEvidence(subject string, e Entry, d *Disposition) {
	url := e.Str("evidence")
	line, _ := json.Marshal(map[string]string{"imported": r.table.Source, "task": subject, "evidence": url, "actor": e.Actor, "ts": e.TS})
	d.Artifact = r.put(line)
	if m := pullRE.FindStringSubmatch(url); m != nil {
		if cs := r.card(subject); cs.prNum == "" {
			cs.prNum = m[1]
		}
	}
}

// comment is message.sent about the card: the body an artifact, inline
// when short.
func (r *replay) comment(subject string, a *actor, e Entry, ts time.Time, d *Disposition) error {
	ev := r.findEvidence(subject, "comment", e.TS)
	text := ""
	if ev != nil {
		text = ev.Text
	}
	payload := map[string]any{"imported": r.table.Source, "kind": "comment", "about": subject}
	if text != "" {
		payload["artifact"] = r.put([]byte(text))
		if len(text) <= maxInline {
			payload["text"] = text
		}
	} else {
		r.note(d, "no comment block in the card matched the entry")
	}
	_, err := r.emit(a, "message.sent", subject, r.withFence(subject, a.s.fp, "message.sent", payload), ts, d)
	return err
}

// respecifyPlan re-specifies a contract at its merged plan once
// plan-unblock cleared it, when the plan file is readable.
func (r *replay) respecifyPlan(subject string, a *actor, ts time.Time, d *Disposition) error {
	p := "plans/" + subject + ".md"
	b := r.repo.file(p, "")
	if b == nil {
		r.note(d, "acceptance stays the card: "+p+" is not readable from --repo")
		return nil
	}
	sha := r.repo.addedCommit(p)
	if sha == "" {
		sha = r.repo.headCommit()
	}
	if sha == "" {
		r.note(d, "acceptance stays the card: --repo has no commit to anchor "+p)
		return nil
	}
	digest := r.put(b)
	s, _ := r.ch.state(subject)
	if s.State != "ready" {
		r.note(d, "plan "+p+" stored as "+digest[:12]+"; the contract is "+s.State+", so it is not re-specified")
		return nil
	}
	payload, _ := json.Marshal(map[string]any{"acceptance": map[string]any{"ref": p + " @ " + sha, "executable": false}})
	if _, err := r.emit(a, "contract.specified", subject, payload, ts, d); err != nil {
		return err
	}
	r.note(d, "re-specified at the merged plan, stored as "+digest[:12])
	return nil
}

// cardRecord is the card file's disposition: its body an artifact,
// and the contract reconciled to the state the card declares when the
// run-log left it elsewhere.
func (r *replay) cardRecord(id string) error {
	c := r.src.Cards[id]
	d := Disposition{Record: c.Path, Artifact: r.put([]byte(c.Raw))}
	target, ok := r.table.States[c.State]
	if !ok {
		return &Refusal{Kind: "import_unmapped", Detail: fmt.Sprintf("%s: card state %q has no row in the transform table", c.Path, c.State)}
	}
	ts, err := parseTS(c.UpdatedAt)
	if err != nil {
		ts = r.now
	}
	s, exists := r.ch.state(id)
	if !exists || s.State != target {
		r.note(&d, "reconciled to the card's declared state "+target+" by the importing operator")
		if err := r.moveTo(id, target, r.opAct, ts, &d); err != nil {
			return err
		}
	}
	r.disp = append(r.disp, d)
	return nil
}

// mail is a v1 mailbox file: stored, and announced as message.sent by
// the importing operator, since a mailbox file names its recipient in
// its path and nothing else the boundary reads.
func (r *replay) mail(p string) error {
	d := Disposition{Record: p}
	digest := r.put([]byte(r.src.Export.Files[p]))
	d.Artifact = ""
	payload, _ := json.Marshal(map[string]string{"imported": r.table.Source, "kind": "mail", "path": p, "artifact": digest})
	if _, err := r.emit(nil, "message.sent", "system", payload, r.now, &d); err != nil {
		return err
	}
	r.note(&d, "stored as "+digest[:12])
	r.disp = append(r.disp, d)
	return nil
}

// manifest renders the pass's dispositions and identities.
func (r *replay) manifest(tableDigest string) *Manifest {
	m := &Manifest{Schema: ManifestSchema, Source: r.table.Source, ExportHead: r.head, Anchor: *r.anchor, Table: tableDigest, Keys: KeysNote, Unresolved: append([]string{}, r.unresolved...)}
	for i, a := range r.ros.all() {
		if a.enrolled == 0 {
			continue
		}
		grants := a.grants
		if grants == nil {
			grants = []string{}
		}
		source := "(the import verifier)"
		if i < len(r.ros.order) {
			source = r.ros.order[i]
		}
		m.Identities = append(m.Identities, IdentityRow{Name: a.name, Source: source, Kind: a.kind, Known: a.known, Fingerprint: a.s.fp, Grants: grants, Enrolled: a.enrolled, Suspended: a.suspended})
	}
	m.Records = append([]Disposition{}, r.disp...)
	m.finish(r.src.RecordCount())
	return m
}

// repoLookup answers the questions the transform asks a repository:
// a cited file's bytes, the commit that added a path, the squash
// commit naming a pull request, the head. An empty repo answers
// nothing, and every answer is cached.
type repoLookup struct {
	dir   string
	cache map[string]string
}

func newRepoLookup(dir string) *repoLookup { return &repoLookup{dir: dir, cache: map[string]string{}} }

// file reads a cited path, at a commit when one is cited and readable
// there, else from the working tree — verbatim, since the bytes are
// what the artifact digest names. The path is confined to the
// repository: a token that escapes it (a crafted id, a parent
// segment) reads nothing.
func (l *repoLookup) file(path, sha string) []byte {
	if l.dir == "" || !repoRelative(path) {
		return nil
	}
	if sha != "" {
		if out, err := gitRaw(l.dir, "show", sha+":"+path); err == nil {
			return out
		}
	}
	b, err := os.ReadFile(filepath.Join(l.dir, filepath.FromSlash(path)))
	if err != nil {
		return nil
	}
	return b
}

// repoRelative reports a clean, slash-separated path beneath the
// repository root: no absolute form, no parent segment, no empty
// segment.
func repoRelative(p string) bool {
	if p == "" || strings.HasPrefix(p, "/") || strings.Contains(p, "\\") {
		return false
	}
	for _, seg := range strings.Split(p, "/") {
		if seg == "" || seg == "." || seg == ".." {
			return false
		}
	}
	return true
}

func (l *repoLookup) cached(key string, fn func() string) string {
	if v, ok := l.cache[key]; ok {
		return v
	}
	v := fn()
	l.cache[key] = v
	return v
}

var fullSHA = regexp.MustCompile(`^[0-9a-f]{40}$`)

func (l *repoLookup) mergeCommit(pr string) string {
	if l.dir == "" {
		return ""
	}
	return l.cached("pr:"+pr, func() string {
		out, err := git(l.dir, "log", "--all", "-n1", "--format=%H", "--fixed-strings", "--grep=(#"+pr+")")
		if err != nil || !fullSHA.MatchString(out) {
			return ""
		}
		return out
	})
}

func (l *repoLookup) addedCommit(path string) string {
	if l.dir == "" {
		return ""
	}
	return l.cached("added:"+path, func() string {
		out, err := git(l.dir, "log", "--all", "-n1", "--format=%H", "--diff-filter=A", "--", path)
		if err != nil || !fullSHA.MatchString(out) {
			return ""
		}
		return out
	})
}

func (l *repoLookup) headCommit() string {
	if l.dir == "" {
		return ""
	}
	return l.cached("head", func() string {
		out, err := git(l.dir, "rev-parse", "HEAD")
		if err != nil || !fullSHA.MatchString(out) {
			return ""
		}
		return out
	})
}

// Names lists every v1 actor name the source attributes anything to.
func (s *Source) Names() []string {
	set := map[string]bool{}
	for _, e := range s.Entries {
		set[e.Actor] = true
	}
	for _, c := range s.Cards {
		set[c.Author] = true
	}
	out := make([]string, 0, len(set))
	for n := range set {
		out = append(out, n)
	}
	sort.Strings(out)
	return out
}

// tableDigest is the sha256 of the table bytes the import ran with.
func tableDigest(b []byte) string { return artifact.Digest(b) }

var _ = transition.TrivialTier
